# Changes here will be overwritten by Copier
_commit: 3c83be0
_src_path: https://github.com/lenskit/lk-project-template.git
owner: Drexel University and contributors
package_name: manylog
project_descr: Collect log messages and progress updates from multiple processes.
project_name: manylog
project_title: ManyLog
require_lint: true
start_year: 2024
typecheck: true
