name: Automated Tests
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test with Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform:
        - macos-latest
        - windows-latest
        - ubuntu-latest
        - macos-14
        python:
        - "3.10"
        - "3.11"
        - "3.12"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}

    - name: Set up dependencies
      run: |
        pip install -U uv
        uv pip install --system -e '.[test]'

    - name: Run tests
      run: python -m pytest --cov=binpickle --cov-report=xml tests

    - name: Save test results
      uses: lenskit/lkbuild/actions/save-test-results@main
      with:
        artifact-name: test-${{matrix.platform}}-py${{matrix.python}}

  report:
    name: Process test results
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Report test results
      uses: lenskit/lkbuild/actions/report-test-results@main
